config/routes.rb
Rails.application.routes.draw do
  resources :categories 
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "registrations"}
  
  resources :orders, only: [:index, :show, :create, :destroy] 

  resources :users
  resources :products do
    resources :comments
  end
  

  root "static_pages#landing_page"

  post 'static_pages/thank_you'

  post 'payments/create'

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # root 'welcome#index'
  mount ActionCable.server => '/cable'

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments

  belongs_to :category
  has_many :categories

  validates :name, presence: true
  validates :category, presence: true

  def self.search(search_term)
    like_operator = Rails.env.production? ? 'ilike' : 'like'
    Product.where("name #{like_operator} ?", "%#{search_term}%")
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowerest_rating_comment
    comments.rating_asc.first
  end

  def average_rating
    comments.average(:rating).to_f
  end

  def views
    $redis.get("product:#{id}")
  end

  def viewed!
    $redis.incr("product:#{id}")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      #byebug
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
    @products = @products.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    @product.viewed!
  end

  # GET /products/new
  def new
    @product = Product.new 
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/ _product.html.erb
<%= link_to product do %>
  <div class ="col-md-4 col-sm-12">
    <p><%= image_tag(product.image_url, class: "img-responsive")%></p>
    <a href="#"><h2><%= product.name %></h2></a>
    <p>Description: <%= product.description %></p>
    <p>Colour: <%= product.colour %></p>
    <p>Price: <%= product.price %></p>
    <%= link_to 'Show', product %>
    <%= link_to 'Edit', edit_product_path(product) %>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div><!--end column-->
<% end %>

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container container-form"> 
    <div class="row">
      <div class="col-md-7 col-xs-12">
        <div class="field"><br>
          <%= form.label :name, class: "label" %>
          <%= form.text_field :name, class: "form-group"%>
        </div>

        <div class="form-field"><br>
          <%= form.label :description, class: "label"%>
          <%= form.text_area :description, class: "texterea"%>
        </div>

        <div>
          <%= form.select :category_id, options_for_select(@categories), prompt: 'Select one!', class: "label" %>
        </div>
      </div>

      <div class="col-md-5 col-xs-12">
        <div class="form-field"><br>
          <%= form.label :image_url, class: "label" %>
          <%= form.text_field :image_url, class: "form-group"%>
        </div>

        <div class= "form-field"><br>
          <%= form.label :colour, class: "label" %>
          <%= form.text_field :colour, class: "form-group" %>
        </div>

        <div class="form-field"><br>
          <%= form.label :price, class: "label" %>
          <%= form.text_area :price, class: "form-group" %>
        </div>

        <div class="actions"><br>
          <%= form.submit class: "btn btn-primary" %>
        </div>           
      </div><!--end column-->          
    </div><!--end row-->        
  </div><!--end container-->    

<% end %>
  

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  <div>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body, class: "form-control", placeholder: "Comments" %>
    </p>
  </div>    
    <p>
      <%= f.label :rating %><br>
      <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit", class: "btn btn-default" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
    <div class ="col-md-4 col-xs-12 products-grid">
      <div class="row">
        <% if product.image_url== nil || product.image_url==""%>
                <%= image_tag("Empty-img.png", class: "img-responsive") %>
              <% else %>
                <%= link_to image_tag(product.image_url, class: "img-responsive img-rounded, btn-link"), product %>
        <% end %>

      <a href="#"><h2><%= product.name %></h2></a>
      <p>Colour: <%= product.colour %></p>
      <p>Price: € <%= product.price %></p>
      <p> Category: <%= link_to product.category.name, category_path(product.category_id) if product.category %></p>
      <%= link_to 'Shop this', product %>
      <% if signed_in? && current_user.admin? %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </div> <!--end row-->    
    </div><!--end column-->
  
<% end %>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-12 col-xs-12">
    <div class= "container container-edit">
      <h1 id= "edith1">Edit Product</h1>
      <%= render 'form', product: @product %>
      <%= link_to 'Show', @product %> |
      <%= link_to 'Back', products_path %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class= "container" id="header-bg">
  <p id="notice"><%= notice %></p>
    <h1>Bikes</h1>
</div>

<div class= "add-product">
  <h2><%= link_to 'New Product', new_product_path %><h2>
</div>
<div class="container container-products">
  <div class= "row">
  <% cache(cache_key_for_products) do %> 
    <% @products.each do |product| %>
      <%= render partial: "product", locals: {product: product} %>
    <% end %>
  <% end %>
  </div><!--end row-->
  <div class="text-center"><%= will_paginate @products %></div>
  <br>
</div><!--end container-fluid-->

app/views/products/new.html.erb
<header class="second">
  <h1>New Product</h1>
</header>

<div class="wrapper">
  <div class="row">
    <div>
      <%= render 'form', product: @product %> 
    </div>    
  </div>  
</div>
<div class="container">
  <div class="row">
    <div>
      <h2 id="backh2"><%= link_to 'Back', products_path %><h2>
    </div>    
  </div>  
</div>

app/views/products/show.html.erb
<header id= "header-bg">
  <h1>Bikes</h1>  
</header>

<div class= "container container-show">
  <div class= "row" data-product-id ="<%= @product.id%>" id= "row-product">
    <div class=" col-md-6 col-sm-8 col-xs-12">
      <p><%= notice %></p>       
        <% if @product.image_url.present? %>
          <%= image_tag(@product.image_url, class: "img-responsive img-zoom", data_zoom_image: "@product.image_url") %>
        <% end %>
    </div>

    <div class="col-md-5 col-sm-4 col-xs-12 column-right">
      <p>
        <strong>Category:</strong>
        <%=@product.category.name%>
      </p>

      <p>
        <strong>Colour:</strong>
          <%= @product.colour %>
      </p>
      <p>
        <strong>Price:</strong>
        €  <%= @product.price %>
      </p>
      <p>Average Rating: <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div> </p>
      <%= form_tag "/payments/create" do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: 'shared/stripe_checkout_button' %>
      <% end %>   
    </div>

    <div class="col-md-8 col-sm-12 col-xs-12 column-description">
    <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
      <h6>
        Views:
        <span class= "badge">
          <%= @product.views %>
        </span>
      </h6>
      <h2><%= @product.name %></h2>
      <p><%= @product.description %></p>
        <%= link_to 'Edit', edit_product_path(@product) %> |
        <%= link_to 'Back', products_path %>
      <hr>
      <div class= "comments">
        <h2>Comments</h2>
        <p><%= @product.highest_rating_comment.try(:rating) %><p>
        <%= render 'new_comment' %>
        <%= render 'comments' %>
      </div>
      <div class="text-center col-xs-12">
        <%= will_paginate @comments %>
      </div>                 
    </div>
  </div><!--end row-->
  <div class="col-xs-12 button-previous">
    <h3 id="previoush2"><%= link_to 'Previous', url_for(:back) %></h3>
  </div> 
</div>