config/routes.rb
Rails.application.routes.draw do
  resources :categories 
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:registrations => "registrations"}
  
  resources :orders, only: [:index, :show, :create, :destroy] 

  resources :users
  resources :products do
    resources :comments
  end
  

  root "static_pages#landing_page"

  post 'static_pages/thank_you'

  post 'payments/create'

  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/landing_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 # root 'welcome#index'
  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My first bike Store</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script:400,700" rel="stylesheet"> 

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!--navbar starts here-->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"
            <%= link_to image_tag("bikeberlin.png"), static_pages_landing_page_path %>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">          
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bikes <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Bikes", products_path %>
                </li>
                <% if can? :read, Category %>
                <li><%= link_to 'Categories', categories_path %></li>
                <% end %>
                <li role="separator" class="divider"></li>
                <li><a href="#">Repair service</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Insurrance</a></li>
              </ul>
            </li>
          </ul>

          <!--Sign in/Register starts here-->
          
          <div class="navbar-form navbar-right">
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_user_registration_path, class: "form-control btn btn-registration ", role:"button" %>
                <% else %>
              <%= link_to('Register', new_user_registration_path, class: "form-control btn btn-registration ", role:"button") %>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "form-control btn btn-registration ", role:"button") %>
              <% else %>
                <%= link_to('Login', new_user_session_path, class: "form-control btn", role:"button") %>
            <% end %>               
          </div>
              
          <!-- Search bar starts here-->
          <%= form_tag("/products", method:"GET", class: "navbar-form navbar-right") do %>
            <div class="form-group">
              <%= label_tag(:q, "Search for:", class: "hidden") %>
              <%= text_field_tag(:q, "", placeholder: "Look for an article", class: "form-control") %>
              <%= submit_tag("Search", class: "btn-search") %>
            </div>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About', static_pages_about_path %></li>
            <li><%= link_to 'Contact', static_pages_contact_path %></li>
            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Sale', static_pages_landing_page_path %>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>-->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Flash Notice Tags -->
    <% if notice %>
      <div id="notice" class="alert alert-warning"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div id="alert" class="alert alert-danger"><%= alert %></div>
    <% end %>

    <div class="page-wrap">
    <%= yield %>
    </div><!--end page-wrap-->

    <footer class="site-footer">
      &copy; 2017 Happy Bikeshop Amsterdam
    </footer>
  </body>
</html>